name: mmdb
description: Movie Database.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^0.13.4
  json_annotation: ^4.9.0

  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/films/posters/
    - assets/actors/headshots/
